### ISSUE TITLE
mqtt quick introduction example

### ISSUE THREAD

**Issue by Gauravmeenu** [eclipse-ditto/ditto-examples#72]
Actually, in this example, the topics mentioned in the addresses section of connection in the source.json and target.json file doesn't work.

**Comment by thjaeckle** [comment]
So which topics do work instead of the ones provided in the tutorial?

**Comment by Gauravmeenu** [comment]
Actually, I'm using pub,sub application console  (mosquitto_sub -h localhost -t my.sensors.notifications/#) as a subscriber and ( mosquitto_pub -h localhost -m '{"temperature": 25, "humidity": 60, "thingId": "my.sensors:sensor01"}' -t my.sensors/sensor01) as a publisher but I can't get any updates in subscriber console only  the state will change in web browser (swagger ui).

**Comment by gunjan-it-engg** [comment]
Actually i also have the same issue

**Comment by gunjan-it-engg** [comment]
Dear Community,

I wanted to address an issue I recently encountered with MQTT server connections and share a solution that can make a big difference.

The Problem:
In my experience, I found that if both the source and target connections to the MQTT server use the same host IP address, it can lead to the connection getting stuck in a loop. This issue was not mentioned in the official examples I consulted.

The Solution:
To resolve this issue, I recommend using different host IP addresses for the source and target connections. This simple adjustment can prevent the loop problem and ensure smoother MQTT server connections.

I hope this tip proves helpful to others in the community facing similar challenges.

Best regards,
